apply plugin: 'com.android.application'
apply plugin: 'com.novoda.android-command'

android {
	compileSdkVersion 32
    defaultConfig {
        applicationId "lyf.jio.activities"
        minSdkVersion 17
        targetSdkVersion 32
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
		// Enabling multidex support.
        multiDexEnabled true

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('androidx.test.espresso:espresso-core:3.6.1', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })


    implementation 'com.google.android.material:material:1.6.1'

    testImplementation 'junit:junit:4.13.2'
    implementation 'com.google.android.gms:play-services-maps:11.0.2'
    implementation 'com.google.android.gms:play-services-ads:25.5.0'

    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
